name: topfish
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intro_slider: ^2.2.8
  bottom_navy_bar: ^5.3.2
  http: ^0.12.0+4
  splashscreen: ^1.2.0
  flutter_launcher_icons: ^0.7.4
  flutter:
    sdk: flutter
  sqflite:
  path:

flutter_icons:
  ios: true
  android: true
  image_path_ios: "asset/images/tik1.png"
  image_path_android: "asset/images/tik1.png"

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  
  assets:
     - assets/icons/icon.png
     - assets/icons/icon1.gif
     - assets/icons/icon2.jpg
     - assets/icons/icon3.png

cupertino_icons: ^0.1.2  
splashscreen: any
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
